// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bili.proto

// Protobuf Java Version: 3.25.0
package com.htdong.common.rpc.bili;

public interface AddNewGuardRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddNewGuardRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 roomId = 1;</code>
   * @return The roomId.
   */
  long getRoomId();

  /**
   * <code>int64 uid = 2;</code>
   * @return The uid.
   */
  long getUid();

  /**
   * <code>string username = 3;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 3;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>int32 guardLevel = 4;</code>
   * @return The guardLevel.
   */
  int getGuardLevel();
}
