// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bili.proto

// Protobuf Java Version: 3.25.0
package com.htdong.common.rpc.bili;

public final class BiliRpcServiceProto {
  private BiliRpcServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbili.proto\032\036google/protobuf/wrappers.p" +
      "roto2_\n\016BiliRpcService\022M\n\020RoomCanUseServ" +
      "er\022\033.google.protobuf.Int64Value\032\032.google" +
      ".protobuf.BoolValue\"\000B=\n\032com.htdong.comm" +
      "on.rpc.biliB\023BiliRpcServiceProtoP\001\242\002\007DEM" +
      "OSRVb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
