log:
  path: /data/logs/htdong
  
zookeeper:
  address: zookeeper://127.0.0.1:2181

dubbo:
  application:
    name: htdong
    check: false
    dump.directory: ${log.path}
  protocol:
    name: dubbo
    port: -1
  registry:
    address: ${zookeeper.address}
  config-center:
    zookeeper:
      address: ${zookeeper.address}

server:
  port: 9760
  servlet:
    context-path: /htdong