dubbo:
  application:
    name: htdong-java
    check: false
    dump.directory: ${log.path}
  protocol:
    name: dubbo
    port: -1
  registry:
    address: ${zookeeper.address}
  config-center:
    address: ${zookeeper.address}
    app-config-file: ${local.conf.file}
    group: htdong

log:
  path: /data/logs/htdong

server:
  port: 9760
  servlet:
    context-path: /htdong
    
zookeeper:
  address: zookeeper://127.0.0.1:2181