log:
  path: /data/logs/htdong
  
zookeeper:
  address: zookeeper://127.0.0.1:2181

dubbo:
  application:
    name: htdong-java
    check: false
    dump.directory: ${log.path}
  protocol:
    name: dubbo
    port: -1
  registry:
    address: ${zookeeper.address}
  config-center:
    address: ${zookeeper.address}
    group: htdong
    config-file: /dubbo/config/dubbo/dubbo.properties
    app-config-file: /dubbo/config/htdong/htdong.properties

server:
  port: 9760
  servlet:
    context-path: /htdong
