zookeeper:
  address: zookeeper://127.0.0.1:2181

dubbo:
  application:
    name: htdong-java
  protocol:
    name: dubbo
    port: -1
  registry:
    address: ${zookeeper.address}
  config-center:
    address: ${zookeeper.address}
    group: htdong
    namespace: htdong

log:
  path: /data/logs/htdong

server:
  port: 9760
  servlet:
    context-path: /htdong